# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'
use_frameworks!


target 'mfgodat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  # Pods for mfgodat
	
     pod 'Alamofire'
     pod 'AlamofireImage'
     pod 'SwiftyJSON'
end
